eureka:
  instance:
    hostname: localhost
  client:
    enabled: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8022