server:
  port: 18003

spring:
  application:
    name: ribbon
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18001/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true